#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd & # Enables window manager specific bindings.
pgrep -x dunst >/dev/null || dunst & # Allows you to recieve notify-send notifications.
pgrep -x polybar >/dev/null || polybar default &
pgrep -x xwallpaper >/dev/null || pick-wallpaper

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a '*':LaunchDialog state=floating center=true sticky=true
