#!/usr/bin/env bash
# Variant of fzf designed to be used in the shell instead of through a subcommand.
# I've seperated this into it's own command because it makes more sense to use a
# bunch of special options for these situations.
#
# This option prevents fzf taking over the entire window (it leaves exactly one
# line for your shell prompt) and reverses it so it appears as if candidates are
# flowing out from your shell prompt.

_fzf() {
    FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS $FZF_SHELL_OPTS" fzf "$@"
}
