#!/usr/bin/env bash
cd_project() {
  sep=$'\t'
  local fzf_args=( -d "$sep" --with-nth 2..
                   --preview 'INCLUDE_DIR=1 preview {1}' --preview-window '~2'
                   --history "${XDG_STATE_HOME:-$HOME/.locale/state}"/fzf/history/paths )
  [ -z "$*" ] || fzf_args+=( -q "$*" )
  local dest
  if dest=$(ls-projects -r -s "$sep" | _mk_fzf "${fzf_args[@]}" | cut -d "$sep" -f 1) &&
      [ -n "$dest" ]; then
    # shellcheck disable=SC2164
    cd "$dest"
  fi
}
