#!/usr/bin/env bash
cd_repo() {
  local fzf_args=( -d '/' --with-nth -1 --preview 'INCLUDE_DIR=1 preview {}' --preview-window '~2'
                   --history "${XDG_STATE_HOME:-$HOME/.locale/state}"/fzf/history/paths )
  [ -z "$*" ] || fzf_args+=( -q "$*" )
  local dest
  if dest=$(ls-projects | _fzf "${fzf_args[@]}") && [ -n "$dest" ]; then
    # shellcheck disable=SC2164
    cd "$dest"
  fi
}
