#!/usr/bin/env bash
edit_executables() {
    local fzf_args
    fzf_args=( -d / --with-nth '-1' --multi --preview 'preview {}'
               --history "${XDG_DATA_HOME:-$HOME/.locale/share}"/fzf/history/paths )
    [ -z "$*" ] || fzf_args+=( -q "$*" )
    ls-exec |
        _fzf "${fzf_args[@]}" |
        select_path
}
