#!/usr/bin/env bash
fzbm() {
  local fzf_args=( -d $'\t' --ansi --with-nth '2..' --multi
                      --bind 'alt-return:execute-silent(xopen {1} &)+down'
                      --bind 'ctrl-y:execute-silent(echo {1} | clip)'
                      --no-hscroll
                      --history "${XDG_STATE_HOME:-$HOME/.locale/state}"/fzf/history/bookmarks )
  [ -z "$*" ] || fzf_args+=( -q "$*" )

  ls-bookmarks -p '' |
    sed '/^javascript:/d' |
    _fzf "${fzf_args[@]}" |
    cut -d $'\t' -f 1 |
    xargs -d '\n' -r xopen
}
