#!/usr/bin/env bash

fzf_dotty() {
  local fzf_args=( -d ':' --with-nth '2..' --multi
                   --bind 'ctrl-y:execute-silent(echo {1} | clip)'
                   --preview 'preview -l bash {1}'
                   --no-hscroll
                   --history "${XDG_STATE_HOME:-$HOME/.locale/state}"/fzf/history/dotty )

  read -r -d '' USAGE <<-EOF
Usage: fzf_dotty [-h] [-a] QUERY
EOF
  read -r -d '' HELP <<-EOF
$USAGE

Optional arguments:
  -h  Show this help message and exit
  -a  Select from all dotty configs, not just modules
EOF

  local all=0
  while getopts 'ha' OPTION; do
    case "$OPTION" in
      h) echo "$HELP"
         return 0 ;;
      a) all=1 ;;
      \?) echo "$USAGE"
          return 1 ;;
    esac
  done
  shift $((OPTIND - 1))
  [ -z "$*" ] || fzf_args+=( --query "$*" )

  local root="${DOTFILES:-${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles}"
  local confs; confs=$(
    if [ "$all" -eq 0 ]; then
      "$root/setup/dotty-ls-modules"
    else
      "$root/setup/dotty-ls-imports"
    fi |
      _mk_fzf "${fzf_args[@]}" |
      cut -d: -f1)
  [ -z "$confs" ] ||
    xargs -r -d '\n' -a <(echo "$confs") "$root/manage" install
}
