#!/usr/bin/env bash
fzf_select() {
    local p
    if [ "$#" -gt 0 ]; then
        p="$*"
        # Always make sure there's a trailing slash on the path.
        [ "${p[${#p}]}" = / ] || p="$p/"
    else
        p="./"
    fi

    # When showing it strip all paths until we reach the cwd.
    local temp="${p//[^\/]}"
    local skip="${#temp}"

    # shellcheck disable=SC2086
    project-files -z ${FZF_SELECT_ARGS:-} -- "$p" |
        _fzf --read0 \
             --multi \
             --preview 'preview {}' \
             --history "${XDG_STATE_HOME:-$HOME/.locale/state}"/fzf/history/paths \
             --delimiter / --with-nth "$((skip+1)).." |
        select_path
}
