#!/usr/bin/env bash
# Present all manual pages in a fzf session and choose
# one or more manual entries to open in your PAGER.

fzman() {
    local fzf_args=( --reverse --multi --no-hscroll
                     --history "${XDG_STATE_HOME:-$HOME/.locale/state}"/fzf/history/man )
    [ -z "$*" ] || fzf_args+=( -q "$*" )

    delimiter=£
    targets=$(apropos -w '*' |
        sed -e 's/\([^ ]\+\) (\([^)]\+\)) *- \?\(.*\)$/\1 (\2)'"$delimiter"'\3/' |
        if hash column 2>/dev/null; then column -s "$delimiter" -t; else tr "$delimiter" ' '; fi |
        _fzf "${fzf_args[@]}" |
        sed 's/^\([^[:space:]]\+\) \?(\([^[:space:]]\+\)).*/\1.\2/')
    [ -z "$targets" ] && return

    # see [[https://unix.stackexchange.com/questions/396397/open-multiple-man-pages-in-less][here]] for how the multi-man command works.
    if [ -n "$FZMAN_CMD" ]; then
        $FZMAN_CMD
    else
        # shellcheck disable=SC2086
        LESSOPEN='|man %s' xargs -r -d '\n' ${MANPAGER:-less} -is
    fi <<< "$targets"
}
