#!/usr/bin/env bash
open_game() {
    local fzf_args=( -d : --with-nth 3.. --ansi --prompt 'Run game: '
                     --history "${XDG_STATE_HOME:-$HOME/.locale/state}"/fzf/history/games )
    [ -z "$*" ] || fzf_args+=( -q "$*" )
    local target
    if target=$(ls-games -p 2>/dev/null | _mk_fzf "${fzf_args[@]}") && [ -n "$target" ]; then
        local protocol url
        IFS=: read -r protocol url _ <<< "$target"
        "${OPENER:-xopen}" "$protocol:$url"
    fi
}
