#!/usr/bin/env bash
select_fsmap() {
    # shellcheck disable=SC2016
    local fzf_args=( --multi -d ' ' --preview 'p={2..}; preview "${p/\~/$HOME}"' --preview-window=25%
                     --history "${XDG_DATA_HOME:-$HOME/.locale/share}"/fzf/history/paths )
    [ -z "$*" ] || fzf_args+=( -q "$*" )
    # shellcheck disable=SC2086
    ls-fsmaps -re ${SELECT_FSMAP_ARGS:-} |
      if command -v column >/dev/null 2>&1; then
          column -s : -t
      else
          # replace the first : (seperator) on each line.
          sed -e 's/\(.\+\):\(.\+\)/\1 \2/'
      fi |
      _fzf "${fzf_args[@]}" |
      sed -e 's/^[^[:space:]]*[[:space:]]\+//' \
          -e "s ^~ $HOME " |
      select_path
}
