#!/usr/bin/env bash

with_emacs() {
    # run a command with editor set to emacsclient.
    local cmd
    cmd="${EMACS_CMD:-emacsclient}"

    [ -z "$EMACS_FLAGS" ] || cmd="$cmd $EMACS_FLAGS"

    if [ "$#" -eq 0 ]; then
        cmd=$(printf %q "$cmd")
        echo -e "EDITOR=${cmd}\nVISUAL=${cmd}"
    else
        EDITOR="$cmd" VISUAL="$cmd" "$@"
    fi
}
