#!/usr/bin/env bash
# -*- +indent: 2 -*- Bash Run Command
#  _               _
# | |             | |
# | |__   __ _ ___| |__  _ __ ___
# | '_ \ / _` / __| '_ \| '__/ __|
# | |_) | (_| \__ \ | | | | | (__
# |_.__/ \__,_|___/_| |_|_|  \___|
#
# This is the main bash configuration file and is sourced whenever you start a
# non-login shell. It doesn't matter whether the shell is interactive or not so
# to speed up performance when running bash shell scripts you should return
# early when being run non-interactively.

# Only run the rest of this file if being sourced interactively
case "$-" in
  *i*) ;;
    *) return ;;
esac

. "$XDG_CONFIG_HOME/shenv"

case "$-" in
  *i*)
    if [ "$INSIDE_EMACS" = 'vterm' ]; then
      PS1=$PS1'\[$(vterm_prompt_end)\]'
    elif [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	    # We have color support; assume it's compliant with Ecma-48
	    # (ISO/IEC-6429). Lack of such support is extremely rare, and such
	    # a case would tend to support setf rather than setaf.
      . "$XDG_CONFIG_HOME/bash/prompt"
    fi
    ;;
esac

shopt -s checkwinsize                                                           # Keep LINES & COLUMNS upto date after every command
shopt -s globstar                                                               # Enable **/* in shell globing
shopt -s autocd                                                                 # cd to path automatically.
shopt -s histappend                                                             # Open history file as a, not w
HISTCONTROL=ignoreboth                                                          # Ignore duplicate lines or lines with spaces.
bind 'set enable-bracketed-paste on'                                            # Allow paste with newlines

if [ -r "$XDG_CONFIG_HOME/bash/bindings" ]; then
  . "$XDG_CONFIG_HOME/bash/bindings"
fi

# Enable programmable completion features
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
