#!/usr/bin/env bash
# -*- mode: sh -*-

# TODO filter out current client
sessions=$(tmux ls -F '#S:#{session_created}:#{session_windows}')

if [ -z "$sessions" ]; then
    tmux new-session
    exit
fi

name_width=$(echo "$sessions" | cut -d: -f1 | wc -L)

sessions=$(echo "$sessions" | awk -F':'         \
           -e 'BEGIN { begin = '$(date +%s)' }' \
           -e '{
    age = begin - $2;
    printf("%s:", $1)
    for (c=0; c < '$name_width' - length($1); c++) printf " "

    if ($3 > 1) {
        printf(" %d windows (made ", $3)
    } else {
        printf(" %d window (made ", $3)
    }

    Y = int(age / 60 / 60 / 24 / 7 / 4 / 12)
    M = int(age / 60 / 60 / 24 / 7 / 4)
    W = int(age / 60 / 60 / 24 / 7)
    D = int(age / 60 / 60 / 24)
    H = int(age / 60 / 60 % 24)
    m = int(age / 60 % 60)
    S = int(age % 60)

    if      (Y == 1) { printf("1 Year") }
    else if (Y >  1) { printf("%d Years", M) }
    else if (M == 1) { printf("1 Month") }
    else if (M >  1) { printf("%d Months", M) }
    else if (W == 1) { printf("1 Week") }
    else if (W >  1) { printf("%d Weeks", W) }
    else if (D == 1) { printf("1 Day") }
    else if (D >  1) { printf("%d Days", D) }
    else if (H == 1) { printf("1 Hour") }
    else if (H >  1) { printf("%d Hours", H) }
    else if (m == 1) { printf("1 Minute") }
    else if (m >  1) { printf("%d Minutes", m) }
    else             { printf("%d Seconds", S) }

    printf(" ago)\n", $3);
}' | sed -E -e 's/^(.+):(.+):(.+)$/\1: \3 window\\s (made \2 ago)/')

if [ "$(echo "$sessions" | wc -l)" -eq 1 ]; then
    choice="$sessions"
else
    choice=$(echo "$sessions" | fzf-tmux | cut -d':' -f 1)
fi

if [ ! -z "$choice" ]; then
    if [ -z "$TMUX" ]; then
        tmux attach-session -t "$choice"
    else
        tmux switch-client -t "$choice"
    fi
fi
