#!/bin/sh
# -*- +indent: 2 -*- Open rar/cbz files with sxiv, adapted from [[https://github.com/muennich/sxiv/issues/301#issuecomment-473677743][here]].

if [ "$#" -eq 0 ]; then
  echo "Usage: $(basename "$0") ARCHIVE [...ARCHIVE]"
  exit 0
fi

set -e

dir="$(mktemp -d -t sxcv-XXX)"
cleanup() {
  [ -n "$dir" ] && rm -r "$dir"
}
trap cleanup EXIT

count=0
while [ "$#" -gt 0 ]; do
  file="$1"; count=$((count+1)); shift
  out=$(printf "%03d" "$count")
  if hash 7z 2>/dev/null; then
    # 7z supports basically everything
    7z x "$file" -o"$dir/$out"
  else
    case "$file" in
      *.zip|*.cbz) unzip "$file" -d "$dir" ;;
      *.rar|*.cbr) unrar e "$file" "$dir" ;;
    esac
  fi #> /dev/null
done

find "$dir" -type f | sort -V | nsxiv "$@" -
