#!/usr/bin/env bash

set -e

# A way to get the absolute path to this directory using
# just shell builtins. (source [[https://stackoverflow.com/a/3915420/6247387][here]]).
root="$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1; pwd -P)"

cd "$root" || exit 1

export HOME="$HOME"
export SHELL="${SHELL:-/usr/bin/bash}"

## Cleanup environment for different platforms.
if [ "$(./bin/ls-platform)" = windows ]; then
  SHELL=$(cygpath -m "$SHELL")
  HOME=$(cygpath -m "$HOME")
fi

# Source and export XDG files for the current platform.
if [ "$("$root"/bin/ls-platform)" = windows ]; then
  xdg_file="$root/core/user-dirs.windows"
else
  xdg_file="$root/core/user-dirs"
fi

# shellcheck disable=SC1090
source "$xdg_file"
source "$root/core/xdgenv"
xdgvars=$(sed -e '/^#/d' -e '/^$/d' -e 's/^\(.\+\)=\(.\+\)$/\1/' "$xdg_file")
IFS=$'\n'
for var in $xdgvars; do
  export "${var?}"
done
export DOTFILES="$root"

./setup/dotty "$@"
