#!/usr/bin/env bash
# Auto decrypt gpg encrypted hledger journals.
#
# All my journal and rules files are GPG encrypted, but hledger only works
# with plaintext files. This script auto decrypts my journals onto my local
# machine and then removes them before exiting.

if [ -z "$LEDGER_FILE" ]; then
  cd "$(dirname "$(dirname "$0")")" || exit 1
else
  if ! [ -e "$LEDGER_FILE" ]; then
    echo "error: hledger-gpg: LEDGER_FILE not found '$LEDGER_FILE'."
    exit 1
  fi
  cd "$(dirname "$(readlink -f "$LEDGER_FILE")")" || exit 1
fi

src_files=$(find . rules/ -mindepth 1 -maxdepth 1 -iname '*.gpg')
if [ -z "$src_files" ]; then
  echo "error: hledger-gpg: failed to find any encrypted files." >&2
  exit 1
fi

build_cmd="echo $(printf %q "$src_files") | parallel --max-procs 1 [ {.} -nt {} ] '||' gpg --batch --yes --quiet --output {.} --decrypt {}"

cleanup() {
  # shellcheck disable=SC1083
  parallel [ -e {.} ] '&&' shred {.} '&&' rm -v {.} <<< "$src_files"
}
cleanup
trap cleanup EXIT SIGHUP

entr -nr sh -c "echo hledger-gpg: decrypting journal files; $build_cmd" <<< "$src_files"
