#!/usr/bin/env bash
# A script to allow using [[https://pythonrepo.com/repo/beancount-fava-python-organization][fava]] as an alternative to [[https://hackage.haskell.org/package/hledger-web][hledger-web]].
#
# hledger-web is a decent and usable UI for hledger, but fava is more
# feature-full and pleasing to the eye. This script converts our journals
# into beancount compatible formats and then starts fava with them. A
# watcher will be setup in the background to update the beancount journal
# when one of the original journal files are modified.

if [ -z "$LEDGER_FILE" ]; then
  cd "$(dirname "$(dirname "$0")")" || exit 1
else
  if ! [ -e "$LEDGER_FILE" ]; then
    echo "error: hledger-fava: LEDGER_FILE not found '$LEDGER_FILE'."
    exit 1
  fi
  cd "$(dirname "$(readlink -f "$LEDGER_FILE")")" || exit 1
fi

export_file="$(mktemp)"
trap 'rm -v $export_file' EXIT SIGHUP

# Need to watch all journals just to ensure watcher is executed properly.
journals=$(find . -mindepth 1 -maxdepth 1 \( -iname '*.journal.gpg' -or \( -iname '*.journal' -and -not -exec [ -e {}.gpg ] \; \) \) -print | sed 's/\.gpg$//')
if [ -z "$journals" ]; then
  echo "error: hledger-fava: failed to find any journal files."
  exit 1
fi
# Ensure decrypted files exist for beancount, but touch the originals so hledger-gpg
# decrypts into the original file anyways.
parallel -r -d '\n' [ -e {} ] '||' touch {} '&&' [ -e {}.gpg ] '&&' touch {}.gpg <<< "$journals"

post_process="sed -e 's/\[\(\[[^]\]\+\)\]\[\([^]\]\+\)\]\]/\2/g' -e 's/ *; *$//'"
export_cmd="hledger print | $post_process"
if which -v ledger2beancount >/dev/null 2>&1; then
  export_cmd="$export_cmd | ledger2beancount -"
fi
export_cmd="$export_cmd > $(printf %q "$export_file")"
eval "$export_cmd"

# Will automatically be killed on SIGHUP.
entr -nrpc sh -c "clear; echo hledger-fava: recompiling beancount journal; $export_cmd" <<< "$journals" &

fava "$export_file"
