#!/usr/bin/env bash
# Variant of [[~/.config/dotfiles/core/autoload/cmds/select_path][select_path]] designed for interactive use with tmux.
_fzf() {
    tmux-popup -h 80% -w 80% -i -o -- fzf --reverse "$@"
}

cd() {
    tmux new-window -c "$*"
}

_edit_files_in_new_tmux_window() {
    # WARN: Will probably crash with really long paths, maybe I
    # should save to a temp file, read and then restore it :?
    local files
    files=$(xargs -r -d '\n' printf "%q ")
    tmux new-window "${VISUAL:-${EDITOR:-vi}} $files"
}
export SELECT_PATH_EDIT_FILE_CMD=_edit_files_in_new_tmux_window

fzf_man_cmd() {
    local targets; targets=$(xargs -r -d "\n" printf "%q ")
    tmux new-window "LESSOPEN='|man %s' ${MANPAGER:-less} -is $targets"
}
export FZF_MAN_CMD=fzf_man_cmd

# shellcheck disable=SC1090
. "$XDG_CONFIG_HOME"/autoloads/cmds/select_path
