#!/usr/bin/env sh
cd_env() {
    select_path "$(env-paths -d |
      if hash column 2>/dev/null; then column -s = -t; else tr '=' ' '; fi |
      fzf --no-multi -d ' ' --preview 'preview {2..}' --preview-window=25% |
      cut -d ' ' -f 2- | sed 's/^ *//')"
}

