#!/usr/bin/env sh
cd_mount() {
    local dest=$(ls-mount |
      if hash column 2>/dev/null; then column -s : -t; else tr ':' ' '; fi |
      fzf --no-multi -d ' ' --preview 'preview {2..}' --preview-window=25% |
      cut -d ' ' -f 2- | sed 's/^ *//')

    cd "$dest" || echo "error: failed to cd: $dest" >&2
}


