#!/usr/bin/env bash
# run fp, then if it succeeds pipe it to the clipboard.
fp_yank() {
    local paths
    if paths=$(file-path "$@"); then
        echo -n "$paths" | clip
    else
        echo "$paths"
    fi
}
