#!/usr/bin/env bash
fztmuxinator() {
  local fzf_args=( -d : --with-nth 3.. --ansi --preview 'preview {1}' --preview-window=50%
                   --history "${XDG_DATA_HOME:-$HOME/.locale/share}"/fzf/history/tmuxinator )
  [ -z "$*" ] || fzf_args+=( -q "$*" )
  local target
  if target=$(ttls -ap | _fzf "${fzf_args[@]}") && [ -n "$target" ]; then
    local conf dir
    IFS=: read -r conf dir _ <<< "$target"
    sh -c '[ -z "$1" ] || cd $1; tmuxinator start --suppress-tmux-version-warning -p $2' start "${dir:-$HOME}" "$conf"
  fi
}
