#!/usr/bin/env bash
# Try to handle one or more paths in the best way possible, this could
# mean changing the cwd or opening your EDITOR on the path.
#
# WARN: Because you can only have one cwd active at a time and this cmd
# accepts multiple paths that can involve one or more directories, only
# the last-most directory passed will be changed to.
# If you supply both files and directories (which you SHOULDN'T do) the
# files will be handled first and then the directory.

select_path() {
    local newdir
    local files
    files=()
    while read -r p; do
        if [ -d "$p" ]; then
            newdir="$p"
        elif [  -f "$p" ]; then
            files+=( "$p" )
        else
            echo "error: can't handle unknown or non-existant path type: $p" >&2
        fi
    done < <(if [ "$#" -gt 0 ]; then printf "%s\n" "$@"; else cat; fi | xargs -r -d '\n' readlink -m)

    # Edit any given files
    if [ "${#files[@]}" -gt 0 ]; then
       printf "%s\n" "${files[@]}" |
           if [ -n "$SELECT_PATH_EDIT_FILE_CMD" ]; then
               $SELECT_PATH_EDIT_FILE_CMD
           else
               # with -r, this only runs if at least one file is found
               # shellcheck disable=SC2086
               xargs -r -d '\n' ${VISUAL-${$EDITOR-vi}}
           fi
    fi

    # Change to any new directories.
    if [ -n "$newdir" ]; then
        # shellcheck disable=SC2164
        cd "$newdir"
    fi
}
