# -*- mode: sh -*-
source "$ZPLUG_HOME/init.zsh"

# Ctrl+Shift+(left|right) to cycle dirstack
zplug 'michaelxmcbride/zsh-dircycle'

# interactive jq
zplug 'reegnz/jq-zsh-plugin'

# complete ssh hostanmes
zplug 'zpm-zsh/ssh'

# asynchronous actions (for prompt), see [[https://github.com/mafredri/zsh-async/issues/42][#42]] for why v1.7.2
zplug 'mafredri/zsh-async', from:github, use:async.zsh, at:v1.7.2

## preview completions/suggestions
#ZSH_AUTOSUGGEST_USE_ASYNC=1
#zplug 'zsh-users/zsh-autosuggestions', from:github

# highlight keywords/commands as you write
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets cursor)
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red'
# remove underlines
ZSH_HIGHLIGHT_STYLES[suffix-alias]="fg=green"
ZSH_HIGHLIGHT_STYLES[precommand]="fg=green"
ZSH_HIGHLIGHT_STYLES[autodirectory]="fg=green"
ZSH_HIGHLIGHT_STYLES[path]="fg=grey"
zplug "zsh-users/zsh-syntax-highlighting", defer:2

# install, then load, if required
if ! zplug check; then zplug install; fi
zplug load

# Shell Options
## shwordsplit      - allows $foo to expand to multiple space delimeted arguments, instead of
##                    just one argument.
## globsubst        - allow glob substitutions to be expanded when done so inside of variables.
##                    eg. foo='*'; find $foo; will behave just as if you type `find *` directly.
## nonotify         - don't interrupt me to let me know a background jobs finished.
## localtraps       - any and trap calls within a function are undone on exit.
## promptpercent    - allow % substitutions in zsh prompts.
## promptsubst      - allow ${} substitutions in zsh prompts.
## appendhistory    - write to history file after every command
## incappendhistory - don't truncate history file.
## histfindnodups   - you can store duplicates, but don't show them as distinct candidates.
## histignorespace  - any command lines beginning with an empty space, doesn't get stored in history.
## histnofunctions  - don't store functions in history as functions. foo() { : }, isn't very readable.
## nohistbeep       - supress any history dings. it's bad enough when a GUI does it.
## autocd           - trying to execute a directory, will change you into it.
## autolist         - ambiguous completion candidate automatically shows options on tab
## automenu         - completion menu (tab to select and cycle) only happens on second tab press
## menucomplete     - prevent automatic insertion of first ambiguous completion target
## autoremoveslash  - removes a trailing slash from completed directories
## completeinword   - allows completions in the middle of a word/argument
setopt shwordsplit globsubst notify localtraps promptpercent \
       promptsubst appendhistory incappendhistory histfindnodups \
       histignorespace histnofunctions nohistbeep autocd nobeep autolist automenu \
       noautoremoveslash completeinword

unsetopt menucomplete
# have completion candidates styled like ls
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# orders directories first, but seperates files from dirs
# even when theres more than enough room for both :sad:.
# zstyle ':completion:*' list-dirs-first true
# zstyle ':completion:*:matches' group 'yes'
# zstyle ':completion:*'         group-name ''

source $XDG_CONFIG_HOME/bindings/zshell

# where to look for autoloads
fpath=("$fpath[@]")

autoload -U compinit && compinit

[ "${SMART_TERM:-0}" -eq 1 ] && . "$XDG_CONFIG_HOME/prompt/zsh"

if [ "$INSIDE_EMACS" = 'vterm' ]; then
    PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'
fi
