# -*- mode: sh -*-
if ! [ -d "$ZGEN_DIR" ]; then
    echo "info: zprofile: zgen installation not found, installing now"
    git clone --quiet https://github.com/tarjoilija/zgen.git "$ZGEN_DIR"
fi
ZGEN_RESET_ON_CHANGE=($ZDOTDIR/.zprofile)
source "$ZGEN_DIR/zgen.zsh"

# zsh-highlight
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets cursor)
# errors and warnings
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red'
# builtins and syntax specific stuff
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=blue'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=blue'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=blue'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[precommand]="fg=blue"

ZSH_HIGHLIGHT_STYLES[global-alias]="fg=green"
ZSH_HIGHLIGHT_STYLES[suffix-alias]="fg=green"
# color for quoted arguments/bodies
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]="fg=blue"
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]="fg=blue"
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]="fg=blue"
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]="fg=black,bold"
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]="fg=black,bold"
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]="fg=black,bold"
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]="fg=cyan"
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]="fg=cyan"

ZSH_HIGHLIGHT_STYLES[assign]="fg=yellow"
ZSH_HIGHLIGHT_STYLES[path]="none"
ZSH_HIGHLIGHT_STYLES[autodirectory]="fg=green"

# zsh-autosuggest
# ZSH_AUTOSUGGEST_USE_ASYNC=1

if ! zgen saved; then
    # Ctrl+Shift+(left|right) to cycle dirstack
    zgen load 'michaelxmcbride/zsh-dircycle'

    # interactive jq
    zgen load 'reegnz/jq-zsh-plugin'

    # complete ssh hostanmes
    zgen load 'zpm-zsh/ssh'

    # asynchronous actions (for prompt)
    zgen load 'mafredri/zsh-async'

    # # preview completions/suggestions
    # zgen load 'zsh-users/zsh-autosuggestions'

    # highlight keywords/commands as you write
    zgen load "zsh-users/zsh-syntax-highlighting"

    zgen save # sync installations
fi

# Shell Options
## shwordsplit      - allows $foo to expand to multiple space delimeted arguments, instead of
##                    just one argument.
## globsubst        - allow glob substitutions to be expanded when done so inside of variables.
##                    eg. foo='*'; find $foo; will behave just as if you type `find *` directly.
## nonotify         - don't interrupt me to let me know a background jobs finished.
## localtraps       - any and trap calls within a function are undone on exit.
## promptpercent    - allow % substitutions in zsh prompts.
## promptsubst      - allow ${} substitutions in zsh prompts.
## appendhistory    - write to history file after every command
## incappendhistory - don't truncate history file.
## histfindnodups   - you can store duplicates, but don't show them as distinct candidates.
## histignorespace  - any command lines beginning with an empty space, doesn't get stored in history.
## histnofunctions  - don't store functions in history as functions. foo() { : }, isn't very readable.
## nohistbeep       - supress any history dings. it's bad enough when a GUI does it.
## autocd           - trying to execute a directory, will change you into it.
## autolist         - ambiguous completion candidate automatically shows options on tab
## automenu         - completion menu (tab to select and cycle) only happens on second tab press
## menucomplete     - prevent automatic insertion of first ambiguous completion target
## autoremoveslash  - removes a trailing slash from completed directories
## completeinword   - allows completions in the middle of a word/argument
setopt shwordsplit globsubst notify localtraps promptpercent \
       promptsubst appendhistory incappendhistory histfindnodups \
       histignorespace histnofunctions nohistbeep autocd nobeep autolist automenu \
       noautoremoveslash completeinword listrowsfirst

unsetopt menucomplete

# have completion candidates styled like ls
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Smart matching of dashed values, e.g. f-b matching foo-bar
zstyle ':completion:*' matcher-list 'r:|[._-]=* r:|=*'

# expand aliases with tab as well (see also <C-x>+a).
zstyle ':completion:*' completer _expand_alias _complete _ignored

# # Don't insert a literal tab when trying to complete in an empty buffer
# zstyle ':completion:*' insert-tab false

# orders directories first, but seperates files from dirs
# even when theres more than enough room for both :sad:.
# zstyle ':completion:*' list-dirs-first true
# zstyle ':completion:*:matches' group 'yes'
# zstyle ':completion:*'         group-name ''

source $XDG_CONFIG_HOME/bindings/zshell

# where to look for autoloads
fpath=("$fpath[@]")

autoload -U compinit && compinit

[ "${smart_term:-0}" -eq 1 ] && . "$XDG_CONFIG_HOME/prompt/zsh"

if [ "$INSIDE_EMACS" = 'vterm' ]; then
    PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'
fi

sourced_zprofile=true
