# -*- mode: sh -*-
if [ -f "$HOME/.profile" ]; then
    . "$HOME/.profile"
fi

export ZDOTDIR="$XDG_CONFIG_HOME/zshell"
export ZPLUG_HOME="$ZDOTDIR/zplug"

if [ -z "$ZSH_COMPDUMP" ]; then
  ZSH_COMPDUMP="${ZDOTDIR:-${ZSH}}/cache/.zcompdump-${ZSH_VERSION}"
fi
