#!/usr/bin/env bash
# -*- mode: sh -*- change working dir in shell to last dir in lf on exit.
# Source: [[https://raw.githubusercontent.com/gokcehan/lf/master/etc/lfcd.sh][github]].
#
# You need to either copy the content of this file to your shell rc file
# (e.g. ~/.bashrc) or source this file directly:
#
#     LFCD="/path/to/lfcd.sh"
#     if [ -f "$LFCD" ]; then
#         source "$LFCD"
#     fi
#
# You may also like to assign a key to this command:
#
#     bind '"\C-o":"lfcd\C-m"'  # bash
#     bindkey -s '^o' 'lfcd\n'  # zsh
#

lfcd() {
    tmp="$(mktemp)"
    signal=EXIT
    [ -n "$BASH_VERSION" ] && signal=RETURN
    trap '\rm -f '"$tmp" "$signal"

    \lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir" || return 1
            fi
        fi
    fi
}
