#!/bin/sh
# Script to use an image as my xsecurelock screensaver.
#
# Use by setting `XSECURELOCK_SAVER=/path/to/xsecurelock_wallpaper`.

list-wallpapers |
  xargs -r -d '\n'                              \
    mpv                                         \
    --no-config                                 \
    --no-audio                                  \
    --no-input-terminal                         \
    --no-stop-screensaver                       \
    --wid="$XSCREENSAVER_WINDOW"                \
    --panscan=1.0                               \
    --image-display-duration=inf
