#!/usr/bin/env bash
# Wrapping command for docker-compose which auto-changes to the media-server
# dotfile directory and uses the correct configuration files for the current
# environment.
#
# Config files
# ------------
# $XDG_CONFIG_HOME/media-server/profile.sh
#   Optional profile file. This will be sourced just before determining which
#   docker-compose files to source. You can use this to override any of the
#   environment variables set by this script (example: PUID) or to set some
#   of the variables described below.
#
# Environment variables
# ---------------------
# MEDIA_SERVER_AUTHELIA=[1]
#   Include an authelia service in the media-server. This will allow you to
#   configure caddy to restrict access to services behind a login wall and
#   even multi-factor authentication.
# MEDIA_SERVER_PROFILES=[PROFILE[,PROFILES...]]
#   Enable one or more media-server profiles. This alternates which services
#   are enabled. Available profiles:
#     anime
#     books
#     comics
#     dashboard
#     movies
#     music
#     qbittorrent
#     socks-proxy
#     test
#     transmission
#     tv-shows
#     vpn

set -e

mediadot="$DOTFILES/prog/media-server"
if ! [ -e "$mediadot" ]; then
  echo "$0: error: Could not find media-server dotfile directory: $mediadot" >&2
  exit 1
fi
cd "$mediadot" || exit 1

export PUID; PUID="$(id -u)"
export PGID; PGID="$(id -g)"
export PWD; PWD=$(pwd)

# By default only the torrents profile is enabled.
MEDIA_SERVER_PROFILES=torrents
is_profile_enabled() {
  case ",$MEDIA_SERVER_PROFILES," in
    *,"$1",*) return 0 ;;
    *)      return 1 ;;
  esac
}

if [ -e "$XDG_CONFIG_HOME/media-server/profile.sh" ]; then
  . "$XDG_CONFIG_HOME/media-server/profile.sh"
fi

if [ -z "$TRANSMISSION_PEER_PORT" ]; then
  export TRANSMISSION_PEER_PORT=51413
fi
if [ -z "$QBITTORRENT_PEER_PORT" ]; then
  export QBITTORRENT_PEER_PORT=51413
fi
if [ -z "$SOCKS_PROXY_PEER_PORT" ]; then
  export SOCKS_PROXY_PEER_PORT=1080
fi

COMPOSE_FILES=( )
add_compose_file() { # [COMPOSE].yml
  COMPOSE_FILES+=( -f "$1.yml" )
  if [ -e "$1.override.yml" ]; then
    COMPOSE_FILES+=( -f "$1.override.yml" )
  fi
}

while read -r compose_file; do
  add_compose_file "${compose_file//.yml/}"
done <<< "$(find . -mindepth 1 -maxdepth 1 -iname '*.yml' -not -iname '*.override.yml' -not -iname '9*' | sort -V)"

[ "${MEDIA_SERVER_AUTHELIA:-0}" -eq 0 ] ||
  add_compose_file 9998-optional.auth
if is_profile_enabled vpn; then
  add_compose_file 9999-optional.vpn
else
  add_compose_file 9999-optional.no-vpn
fi

if is_profile_enabled socks-proxy; then
  if ! is_profile_enabled vpn; then
    echo "error: $0: The socks-proxy module requires vpn profile to be enabled" >&2
    exit 1
  fi
  add_compose_file 9999-optional.socks-proxy
fi

export COMPOSE_PROFILES="${MEDIA_SERVER_PROFILES}"

exec docker-compose "${COMPOSE_FILES[@]}" "$@"
