#!/bin/sh

wall_config="$XDG_CONFIG_HOME/wallpapers"
found=0
while read -r it; do
  if [ -e "$it" ]; then
    found=1
    echo "$it"
  else
    echo "error: list-wallpaper: wallpaper path from $wall_config not found: $it." >&2
  fi
done < "$wall_config"

if [ "$found" = 1 ]; then
  exit 0
fi

find -L "$XDG_PICTURES_DIR/wallpapers" -mindepth 1 -maxdepth 1 -type f
