#!/bin/sh
# -*- +indent: 2 -*- Pick a new x-wallpaper.

wall=$(ls-wallpapers | sort -R | head -n1)
if [ -z "$wall" ]; then
  echo "error: pick-wallpaper: no wallpapers found, clearing xwallpaper." >&2
  xwallpaper --clear
  exit 1
fi

if xwallpaper --zoom "$wall"; then
  printf "%s" "$wall" > "$XDG_DATA_HOME/wallpaper"
fi
