#!/usr/bin/env python3
"""Status misc segment for showing NordVPN connection status."""
# pylint: disable=no-member

import logging
import re
from distutils.spawn import find_executable as which
from typing import Callable

from lib.shared import run_process
from lib.status_misc.segment import StatusMiscSegment


class NordVPNSegment(StatusMiscSegment):
    """Status line segment showing NordVPN status."""

    name = "nordvpn"

    @classmethod
    def parser_args(
        cls, parser: "argparse.ArgumentParser", flag: Callable[[str], str]
    ) -> None:
        nvpn_group = parser.add_argument_group("Nord VPN")
        super().parser_args(nvpn_group, flag)

        nvpn_group.add_argument(
            flag("icon"),
            default="N",
            metavar="ICON",
            help="Icon shown to indicate nordvpn status.",
        )
        nvpn_group.add_argument(
            flag("hide"),
            action="store_true",
            help="Hide nordvpn status when disconnected",
        )
        nvpn_group.add_argument(
            flag("active-style"),
            default="",
            metavar="STYLE",
            help="Styling for an active nordvpn connection.",
        )
        nvpn_group.add_argument(
            flag("inactive-style"),
            default="",
            metavar="STYLE",
            help="Styling for an inactive nordvpn connection.",
        )

    # pylint: disable=invalid-overridden-method
    async def render(self):
        """Nordvpn status-line section."""
        # pylint: disable=no-member
        if not which("nordvpn"):
            logging.debug(
                "Skipping segment=%s because nordvpn is not installed.", self.name
            )
            return None
        returncode, stdout, _stderr = await run_process(
            ["nordvpn", "status"], encoding="utf-8"
        )
        if returncode != 0:
            logging.warning(
                "Warning failed to run nordvpn process for segment=%s", self.name
            )
            return None
        ip_address = ""
        match = re.search(r"Server IP: (.+)", stdout, flags=re.IGNORECASE)
        if not match:
            if self.hide:
                return None
        elif match:
            ip_address = " " + match[1]
        return (
            self._style(
                self.icon, self.active_style if ip_address else self.inactive_style
            )
            + ip_address
        )


if __name__ == "__main__":
    NordVPNSegment.main()
