#!/bin/sh

# Sync mail files from all configured remotes
mbsync --verbose -c "$XDG_CONFIG_HOME"/isync/mbsyncrc all

# Refresh the notmuch mail database, attaching the new tag to any new mail
notmuch new

# Automatically read and flag any emails from myself
notmuch tag -new -unread +flagged -- tag:new and from:"mohsin kaleem"

# Automatically mark developer related content
notmuch tag -new +dev -- tag:new and from:help-debbugs@gnu.org
notmuch tag -new +dev -- tag:new and from:@github.com

# Remove new tag and attach defaults for rest of new mail
notmuch tag +inbox +unread -new -- tag:new
