#!/usr/bin/env bash
# Print out the environment variables that should be set for the current
# jellyfin-docker environment. This is used mostly for the tmuxp command
# but can be reused for other purposes.

# These variables make docker-compose skip trying to mount these directories.
for it in \
    JELLYFIN_SKIP_DOWNLOAD:"$XDG_DOWNLOAD_DIR"    \
    JELLYFIN_SKIP_MUSIC:"$XDG_MUSIC_DIR"          \
    JELLYFIN_SKIP_MOVIES:"$XDG_VIDEOS_DIR/movies" \
    JELLYFIN_SKIP_TV:"$XDG_VIDEOS_DIR/tv"         \
    JELLYFIN_SKIP_AMV:"$XDG_VIDEOS_DIR/AMV"       \
    JELLYFIN_SKIP_MANGA:"$HOME/media/manga"; do
  IFS=: read -r var location <<< "$it"
  [ -e "$location" ] ||
    echo export "$var"="$XDG_CACHE_HOME/jellyfin.empty"
done
