#!/usr/bin/env bash
fzf_docker_container() {
  local USAGE HELP
  read -r -d '' USAGE <<EOF
Usage: fzf_docker_container [-h] [-c CMD]
EOF

  read -r -d '' HELP <<EOF
$USAGE

  Interactively select and run an interactive command
  within one of the already running containers managed
  by docker.

Optional arguments:
  -h      Show this help message and exit
  -c CMD  Specify command to run within container
EOF

  local cmd='bash -li'
  local args=(
    exec --interactive --tty
    --env COLUMNS="$(tput cols)"
    --env LINES="$(tput lines)"
    --env TERM=xterm-256color
  )
  while getopts 'hc:' OPTION; do
    case "$OPTION" in
      h) echo "$HELP"
         return 0 ;;
      \?) echo "$USAGE"
          return 1 ;;
      c) cmd="$OPTARG" ;;
    esac
  done

  local sep=$'\t'
  local fzf_args=(
    -d "$sep" --ansi --with-nth '2..'
    --history "${XDG_STATE_HOME:-$HOME/.locale/state}"/fzf/history/docker
  )

  local id containers
  if containers=$(ls-docker-containers) &&
      [ -n "$containers" ] &&
      id=$(ls-docker-containers |
            _mk_fzf "${fzf_args[@]}" |
            cut -d"$sep" -f1) &&
      [ -n "$id" ]; then
    docker "${args[@]}" "$id" bash -c "$cmd"
  fi
}
