#!/usr/bin/env bash
_fzf() {
    fzf "$@"
}

cd() {
    lf -remote "send $id cd \"$*\""
}

_edit_files_by_selecting_them() {
    local file
    file=$(tail -n1)
    [ -n "$file" ] && lf -remote "send $id select \"$file\""
}
export SELECT_PATH_EDIT_FILE_CMD=_edit_files_by_selecting_them

# shellcheck disable=SC1090
. ~/.config/autoloads/cmds/select_path
