#!/usr/bin/env bash
# -*- +indent: 2 -*-
# combine all [[https://wiki.archlinux.org/index.php/Pass][pass]] records into a single YAML file

pass_all() {
  ls-pass -C |
    grep -v tomb |
    cut -d: -f2 |
      while read -r it; do
        echo "$it:"
        pass -- "$it" |
          sed -e '1s/.*/password: \0/' -e 's/.*/  \0/' -e '$s/$/\n/'
      done |
    preview -l yaml -
}
