#!/bin/sh
# Parse out all the current environment variables related to
# non-temporary XDG paths and output them in a form that can
# be pushed back into ~/.config/user-dirs.dirs.

printenv -0 |
  tr -d '\n' |
  tr '\0' '\n' |
  grep '^XDG_[^=]\+_\(DIR\|HOME\)' |
  grep -v '^XDG_RUNTIME_DIR' |
  awk -F = -v home="$HOME" -e '
BEGIN { OFS = FS }

match($2, home) == 1 {
  sub(home, "$HOME", $2)
}

{ print($0) }
'
