#!/usr/bin/env bash
# -*- +indent: 2 -*- notmuch initial tagging script.
#
# This script is run by [[man:notmuch-hooks][notmuch]] immediately after any new mail
# has been added to the inbox. This makes it perfect for auto-
# tagging new emails and dispatching update notifications.

set -e

prog="$(basename "$0")"

echo
echo "###############################################################################"
echo "#                           Notmuch Post New Script                           #"
echo "###############################################################################"
echo

local_file=$(dirname "$0")/post-new.local
if [ -x "$local_file" ]; then
  echo "###############################################################################"
  echo "#                         Notmuch Local Tagging Script                        #"
  echo "###############################################################################"
  echo

  "$local_file" "$@"
fi

echo "###############################################################################"
echo "#                       Notmuch New Mail Tagging Script                       #"
echo "###############################################################################"
echo

tag_config=$(dirname "$0")/post-new.tags
if [ -e "$tag_config" ]; then
  sed -e '/^#.*/d' -e '/^[[:space:]]*$/d' "$tag_config" | notmuch tag --batch
else
  echo "error: $prog: No tag config file found at $local_file" >&2
fi

echo "###############################################################################"
echo "#                         Notmuch Expunge Deleted Mail                        #"
echo "###############################################################################"
echo

archive_script=$(dirname "$0")/post-new.archive
if [ -x "$archive_script" ]; then
  "$archive_script" "$@"
fi
