#!/usr/bin/env python3

import functools
import logging
import os
import pathlib
import shlex
from typing import Any, Dict, List, Optional, TextIO

import click
import yaml

COMMON_WORSPACE_DIRECTORIES = ["/workarea", "/workspace"]

LOCAL_PROFILE_DIRECTORY = pathlib.Path(".lcldev") / "mk"
LOCAL_COMPOSE_FILE = LOCAL_PROFILE_DIRECTORY / "docker-compose.override.yml"

MAIN_COMPOSE_FILES = [
    pathlib.Path("docker-compose.yaml"),
    pathlib.Path("docker-compose.yml"),
    pathlib.Path(".dev-compose.yml"),
]

EXTRA_COMPOSE_FILES = [
    pathlib.Path("docker-compose.override.yaml"),
    pathlib.Path("docker-compose.override.yml"),
    pathlib.Path(".devcontainer/docker-compose.yml"),
    LOCAL_COMPOSE_FILE,
]

PROFILE_ALIASES = {
    "bce": "bbcmake-env",
    "bceb": "bce --action=build",
    "bcet": "bce --action=ctest",
}


@functools.lru_cache()
def get_main_compose_file() -> Optional[pathlib.Path]:
    logging.debug("Finding main compose file")
    for file in MAIN_COMPOSE_FILES:
        logging.debug("Looking for compose file at path=%s", file)
        if file.exists():
            return file

    logging.warning("Failed to locate main compose file")
    return None


@functools.lru_cache()
def get_extra_compose_files() -> List[pathlib.Path]:
    logging.debug("Finding extra compose files")
    files = []
    for file in EXTRA_COMPOSE_FILES:
        logging.debug("Looking for extra compose file at path=%s", file)
        if file.exists():
            files.append(file)

    return files


def _removeprefix(string: str, prefix: str) -> str:
    if string.startswith(prefix):
        string = string[len(prefix) :]
    return string


def _read_compose(file: pathlib.Path) -> Dict[str, Any]:
    with file.open("r") as file_handle:
        return yaml.safe_load(file_handle)


def detect_default_service(
    project_dir: pathlib.Path, compose_file: pathlib.Path
) -> Optional[str]:
    logging.debug(
        "Detecting default service for project=%s and compose-file=%s",
        project_dir,
        compose_file,
    )
    services = list(_read_compose(compose_file).get("services", {}))

    if len(services) == 0:
        return None
    elif len(services) == 1:
        logging.debug("Using single configured service=%s", services[0])
        return services[0]

    project_name = project_dir.absolute().name
    possible_services = {
        project_name,
        _removeprefix(project_name, "s-"),
        _removeprefix(project_name, "m-"),
        _removeprefix(project_name, "a-"),
        "dev",
    }
    for service in possible_services:
        logging.debug("Checking for service with name=%s", service)
        if service in services:
            return service
    return None


def detect_default_workdir(
    project_dir: pathlib.Path, compose_file: pathlib.Path
) -> Optional[pathlib.Path]:
    # TODO: Support default workdir detection.
    return None


def _install_local_dev_files(root: pathlib.Path) -> None:
    gdb_root = pathlib.Path(os.path.expandvars("$DOTFILES/prog/gdb"))

    for file in gdb_root.glob("**/*"):
        if file.is_dir() or file.name.startswith("."):
            continue

        dest = root / "gdb" / file.relative_to(gdb_root)
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.exists():
            dest.unlink()
        os.link(file, dest)


def _write_local_dev_profile(
    external_root: pathlib.Path, container_root: pathlib.Path, profile: TextIO
) -> None:
    NEWLINE = "\n"
    gdb_init = container_root / LOCAL_PROFILE_DIRECTORY / "gdb" / "gdbinit"
    gdb_bsl = gdb_init.parent / "gdb_bsl.py"

    profile.write(
        f"""\
###############################################################################
#                                    Setup                                    #
###############################################################################

sudo=
if command -v sudo >/dev/null 2>&1; then
  sudo=sudo
fi

###############################################################################
#                              Local Dev Profile                              #
###############################################################################

export TERMINFO=/usr/share/terminfo
export   LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Git setup
git config --global --add safe.directory '*'

if ! [ -e {shlex.quote(str(external_root.parent))} ]; then
  ${{sudo:-}} mkdir -p {shlex.quote(str(external_root.parent))}
  ${{sudo:-}} ln -s {shlex.quote(str(container_root))} {shlex.quote(str(external_root))}
fi

# NOTE: You may have to reinstall the devtoolset for your gcc version for the
# standard library pretty printers here to work as expected. Double check
# /opt/bb/share/gdb/python/. You can install it with:
#   yum install devtoolset-10

# GDB setup
export GDBINIT={shlex.quote(str(gdb_init))}
mkdir -p ~/.cache/gdb
alias gdb='gdb --silent -nh -x "$GDBINIT" --eval-command "source {shlex.quote(str(gdb_bsl))}"'

# Aliases
{NEWLINE.join(f'alias {shlex.quote(alias)}={shlex.quote(value)}' for alias, value in PROFILE_ALIASES.items())}
"""
    )


###############################################################################
#                                     Main                                    #
###############################################################################


@click.group()
@click.option(
    "--log-level",
    type=lambda lvl: getattr(logging, lvl.upper()),
    metavar="LEVEL",
    default="INFO",
    help="Set verbosity of logging output.",
)
def cli(log_level: int) -> None:
    try:
        from mohkale.pylog import use_config as use_logging_config
    except ImportError:
        logging.basicConfig(level=log_level)
    else:
        use_logging_config("bb-local-dev", level=log_level)


@cli.command()
@click.option(
    "-c",
    "--service-name",
    metavar="SERVICE_NAME",
    help="Run in composable mode with SERVICE_NAME.",
)
@click.option(
    "-C",
    "--no-composable",
    is_flag=True,
    show_default=True,
    help="Do not attempt to create composable build.",
)
@click.option(
    "-d",
    "--distribution",
    metavar="DPKG_DISTRIBUTION",
    help="Override the DPKG distribution to pull packages from.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    show_default=True,
    help="Echo out ide-magic command instead of running it.",
)
def magic(
    service_name: Optional[str],
    no_composable: bool,
    distribution: Optional[str],
    dry_run: bool,
) -> None:
    """Ide-magic proxy command."""
    if no_composable:
        service_name = None
    elif not service_name:
        logging.info("No service name set, trying to auto-detect")
        main_compose_file = get_main_compose_file()
        if main_compose_file:
            service_name = detect_default_service(pathlib.Path("."), main_compose_file)
            if not service_name:
                logging.warning("Could not determine service for compose project")
                service_name = click.prompt("Enter service for compose project")

    magic_command = ["ide-magic"]
    if service_name:
        magic_command.extend(["--composable", service_name])
    if distribution:
        magic_command.extend(["--distribution", distribution])

    if dry_run:
        print(" ".join(shlex.quote(it) for it in magic_command))
        return

    os.execlp(magic_command[0], *magic_command)


@cli.command()
@click.option(
    "-p",
    "--workdir",
    metavar="PATH",
    type=pathlib.Path,
    help="Specify path to working directory within container.",
)
@click.pass_context
def install(ctx, workdir: Optional[pathlib.Path]) -> None:
    if not workdir:
        main_compose_file = get_main_compose_file()
        if main_compose_file:
            workdir = detect_default_workdir(pathlib.Path("."), main_compose_file)
        else:
            logging.warning("Could not locate local main-compose file")
        if not workdir:
            logging.warning("Could not determine working directory for compose project")
            workdir = pathlib.Path(
                click.prompt("Enter working directory for compose project")
            )

    src_dir = pathlib.Path(".").absolute()
    local_profile_dir = src_dir / LOCAL_PROFILE_DIRECTORY

    # TODO: Auto install compose configurations to LOCAL_COMPOSE_FILE.
    _install_local_dev_files(local_profile_dir)
    with (local_profile_dir / "profile").open("w", encoding="utf-8") as file:
        _write_local_dev_profile(src_dir, workdir, file)


@cli.command(context_settings={"ignore_unknown_options": True})
@click.option(
    "--dry-run",
    is_flag=True,
    show_default=True,
    help="Echo out compose command instead of running it.",
)
@click.argument("compose_args", nargs=-1, type=click.UNPROCESSED)
@click.pass_context
def compose(ctx, dry_run: bool, compose_args: click.UNPROCESSED) -> None:
    """Run docker-compose with local-dev compose files."""
    main_compose_file = get_main_compose_file()
    if not main_compose_file:
        logging.error("Could not find main project compose file")
        ctx.exit(1)

    compose_command = ["docker-compose", "-f", str(main_compose_file)]
    for extra_file in get_extra_compose_files():
        compose_command.extend(["-f", str(extra_file)])

    compose_command.extend(compose_args)

    if dry_run:
        print(" ".join(shlex.quote(it) for it in compose_command))
        return

    os.execlp(compose_command[0], *compose_command)


if __name__ == "__main__":
    cli()
