#!/usr/bin/env bash
# -*- +indent: 2 -*- Bash profile.
#  _               _                           __ _ _
# | |__   __ _ ___| |__       _ __  _ __ ___  / _(_) | ___
# | '_ \ / _` / __| '_ \     | '_ \| '__/ _ \| |_| | |/ _ \
# | |_) | (_| \__ \ | | |    | |_) | | | (_) |  _| | |  __/
# |_.__/ \__,_|___/_| |_|____| .__/|_|  \___/|_| |_|_|\___|
#                      |_____|_|
#
# This script overrides [[file:~/.profile][~/.profile]] and is run for login shells.
# Unfortunately bash itself doesn't run [[file:~/.bashrc][~/.bashrc]] when running a login
# shell even if that shell is interactive. To get around this you have
# to source ~/.bashrc in ~/.profile, but that conflicts with other shells
# so instead [[file:~/.bash_profile][~/.bash_profile]] is required.

. "$HOME"/.profile
. "$HOME"/.bashrc
