#!/bin/sh
# Proxy for the clojure REPL which adds readline support.
breakchars="(){}[],^%$#@\"\";:''|\\"
CLOJURE_DIR=~/clojure
CLOJURE_JAR="$CLOJURE_DIR"/clojure.jar
if [ $# -eq 0 ]; then
     exec rlwrap --remember -c -b "$breakchars" \
        -f "$HOME"/.clj_completions \
         java -cp "$CLOJURE_JAR" clojure.main
else
     exec java -cp "$CLOJURE_JAR" clojure.main "$1" -- "$@"
fi
