#!/usr/bin/env bash
# Usage: cut-add {move|copy}
#
# shellcheck disable=SC2154,SC3003

files=$(tail -n +2 "$XDG_DATA_HOME/lf/files")
newline=$'\n'

# Remove empty lines from the file list, because they keep messing
# up the selection.
new_files=$(echo "$files${newline}$fx" | sort | uniq | sed --quiet -e '/^$/d' -e 'p')

printf "%s\n%s\n" "$1" "$new_files" >"$XDG_DATA_HOME/lf/files"
lf -remote "send $id unselect${newline}send sync"
